### ISSUE TITLE
请求转移至 ParaTranz

### ISSUE THREAD

**Issue by bruceCzK** [gamesyofo/Tropico6-part-zh-hans#1]
你好，我是52汉化组的成员，paratranz.cn 这个网站是我自己搞的一个翻译平台，类似国外的 OneSky、Crowdin 等在线翻译平台，现在已经收纳了200多个项目了。

网站不需要单独注册，使用 Github 账号就可以登录。创建项目，导入文本之后，就可以供多人同时在线翻译，另外也包含导入、导出、评论、私信等功能。

具体可以移步网站 https://paratranz.cn , 查看各个项目进行了解。

![TIM截图20190405231833](https://user-images.githubusercontent.com/8399711/55638216-4190e980-57f9-11e9-928e-468043ece116.jpg)
![TIM截图20190405231845](https://user-images.githubusercontent.com/8399711/55638217-4190e980-57f9-11e9-9b35-662168f6fc50.jpg)
![TIM截图20190405231916](https://user-images.githubusercontent.com/8399711/55638218-42298000-57f9-11e9-8930-d319d9ae0d73.jpg)

**Comment by ziben** [comment]
这个不错，可以大家一起来翻译和润色

**Comment by gamesyofo** [comment]
怎么操作

**Comment by gamesyofo** [comment]
但我不负责后期维护，我随时都会弃坑

**Comment by bruceCzK** [comment]
@gamesyofo 要么你加我一下Q，我现在主要是卡在封包这一步了，这个搞定了后面就简单了。

**Comment by bruceCzK** [comment]
我自己研究出来了，项目已经建好了 https://paratranz.cn/projects/310

**Comment by gamesyofo** [comment]
我下下来怎么不对
